name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  library-apple:
    runs-on: macos-12
    strategy:
      matrix:
        xcode:
          - '14.2'
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test-library-xcode

  library-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.7
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Run tests
        run: make test-library

  examples:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.2.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make build-examples
