name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  library-apple:
    runs-on: macos-12
    strategy:
      matrix:
        xcode:
          - '14.0'
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test-library-xcode
      - name: Compile documentation
        if: ${{ matrix.xcode == '14.0' }}
        run: make test-docs

  library-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.6
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Run tests
        run: make test-library

  examples:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test-examples
