name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  library:
    runs-on: macos-12
    strategy:
      matrix:
        xcode: [13.2.1, 13.4]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test-library-xcode
      - name: Compile documentation
        if: ${{ matrix.xcode == '13.4' }}
        run: make test-docs

  examples:
    runs-on: macos-12
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.4.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test-examples

  linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.6
    steps:
      - uses: actions/checkout@v1.0.0
      - name: Run tests
        run: make test-library
