name: CI
on: push

jobs:
  test-macOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: SwiftPM Build
        run: swift test --enable-test-discovery
  test-iOS:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - name: xcodebuild
        run: |-
          xcodebuild \
            -scheme Buildkite \
            -destination "platform=iOS Simulator,OS=latest,name=iPhone 12 Pro Max" \
            -enableCodeCoverage YES \
            -quiet \
            build test
  test-linux:
    runs-on: ubuntu-latest
    container:
      image: swift:5.4
    steps:
      - uses: actions/checkout@v1.0.0
      - name: SwiftPM Build
        run: swift test --enable-test-discovery
